// <auto-generated />
using System;
using Bank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230427091102_ImagesAded")]
    partial class ImagesAded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bank.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardCvv")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("CardExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("CardPin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("UserImage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardCvv = "123",
                            CardExpirationDate = new DateTime(2024, 4, 27, 13, 11, 1, 968, DateTimeKind.Local).AddTicks(5707),
                            CardNumber = "1111222233334444",
                            CardPin = "1234",
                            LastName = "Doe",
                            Name = "John",
                            UserImage = "https://i.pinimg.com/originals/ae/ec/c2/aeecc22a67dac7987a80ac0724658493.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CardCvv = "456",
                            CardExpirationDate = new DateTime(2024, 4, 27, 13, 11, 1, 968, DateTimeKind.Local).AddTicks(5718),
                            CardNumber = "5555666677778888",
                            CardPin = "5678",
                            LastName = "Doe",
                            Name = "Jane",
                            UserImage = "https://randomuser.me/api/portraits/women/65.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
